# Generated by Django 5.1.2 on 2024-12-24 00:50

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boeuf',
            fields=[
                ('id_boeuf', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('sexe', models.CharField(choices=[('M', 'Mâle'), ('F', 'Femelle')], max_length=1)),
            ],
            options={
                'verbose_name': 'Bœuf',
                'verbose_name_plural': 'Bœufs',
            },
        ),
        migrations.CreateModel(
            name='Eleveur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tel', models.CharField(max_length=15, verbose_name='Téléphone')),
            ],
            options={
                'verbose_name': 'Éleveur',
                'verbose_name_plural': 'Éleveurs',
            },
        ),
        migrations.CreateModel(
            name='DonneeBoeuf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('humidite', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Humidité (%)')),
                ('temp_interne', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Température interne (°C)')),
                ('temp_externe', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Température externe (°C)')),
                ('mvt_detecte', models.BooleanField(default=False, verbose_name='Mouvement détecté')),
                ('position', models.JSONField(help_text="Format: {'lat': float, 'lng': float}")),
                ('freq_cardiaque', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)], verbose_name='Fréquence cardiaque (bpm)')),
                ('freq_respiratoire', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Fréquence respiratoire (rpm)')),
                ('boeuf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donnees', to='recover_data.boeuf')),
            ],
            options={
                'verbose_name': 'Donnée bœuf',
                'verbose_name_plural': 'Données bœufs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='boeuf',
            name='eleveur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boeufs', to='recover_data.eleveur'),
        ),
    ]
