# Generated by Django 5.1.2 on 2024-12-26 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recover_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donneeboeuf',
            name='freq_cardiaque',
        ),
        migrations.RemoveField(
            model_name='donneeboeuf',
            name='freq_respiratoire',
        ),
    ]
