# Generated by Django 5.1.2 on 2024-12-26 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recover_data', '0002_remove_donneeboeuf_freq_cardiaque_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donneeboeuf',
            name='temp_externe',
        ),
    ]
