# Generated by Django 5.1.2 on 2025-01-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recover_data', '0003_remove_donneeboeuf_temp_externe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('mail_admin', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(default='password123', max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='eleveur',
            name='mot_de_passe',
            field=models.CharField(default='password123', max_length=128),
        ),
    ]
