# Generated by Django 5.1.2 on 2025-01-12 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recover_data', '0004_administrateur_eleveur_mot_de_passe'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeConnexionAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recover_data.administrateur')),
            ],
        ),
    ]
